OlSoftwareFront/Controllers/AspiranteController.cs
using Microsoft.AspNetCore.Mvc;
using OlSoftwareFront.DataAccess;

namespace OlSoftwareFront.Controllers
{
    public class AspiranteController : Controller
    {


        private readonly AspiranteService aspiranteService ;

        public AspiranteController()
        {
            this.aspiranteService = new AspiranteService();
        }
        public async Task<IActionResult> Index()
        {
            string token = HttpContext.Session.GetString("token");
			var list = await this.aspiranteService.GetAspirantes(token);
            return View(list);
        }
    }
}

OlSoftwareFront/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace OlSoftwareFront.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OlSoftwareFront/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using OlSoftwareFront.DataAccess;
using OlSoftwareFront.Model;

namespace OlSoftwareFront.Controllers
{
    public class LoginController : Controller
    {


        private readonly AutenticationService autenticationService;

        public LoginController()
        {
            this.autenticationService =  new AutenticationService();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Autentication autentication)
        {
			


			var result = await this.autenticationService.Autentication(autentication);
            if (result is not null)
            {            
				HttpContext.Session.SetString("token", result.token); 			 				 
                return Redirect("Dashboard");
            }  
            else
                return View("Index");

           
        }
    }
}

OlSoftwareFront/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;

namespace OlSoftwareFront.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OlSoftwareFront/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace OlSoftwareFront.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OlSoftwareFront/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OlSoftwareFront.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OlSoftwareFront/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OlSoftwareFront.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OlSoftwareFront/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a href="@Url.Action("Index", "Login")" class="btn btn-outline-primary">Login</a>
</div>

OlSoftwareFront/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OlSoftwareFront</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OlSoftwareFront.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OlSoftwareFront</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                         

                        </li>
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OlSoftwareFront - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OlSoftwareFront/Views/Aspirante/Index.cshtml
@model List<OlSoftwareFront.Model.AspirantesResponse>


<div class="d-flex flex-wrap flex-row">

	<div class="table-responsive">

		<table class="table table-bordered table-striped" id="tblproductos">
			<thead>
				<tr>
					<th>Nombres</th>
					<th>Docuemento</th>
					<th>Telefono</th>
					<th>Correo</th>
					<th>Accion</th>
				</tr>

			</thead>
			<tbody>

				@foreach (var usuario in Model)
				{
					<tr>
						<td>@usuario.nombres</td>
						<td>@usuario.numDocumento</td>
						<td> @usuario.telefono</td>
						<td> @usuario.email</td>

						</tr>
				}
			</tbody>

		</table>

	</div>

</div>

OlSoftwareFront/Views/Dashboard/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OlSoftwareFront</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OlSoftwareFront.styles.css" asp-append-version="true" />
</head>


bulk of the card's content.

Copy
<div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
    <div class="card-header">Aspirante</div>
    <div class="card-body">
        
        <a class="card-title text-white" href="@Url.Action("Index", "Aspirante")"><h5 class="card-title">Ver Aspirantes</h5></a>
    </div>
</div>
<div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header">Prueba</div>
    <div class="card-body">
        
        <a href="@Url.Action("Index", "Login")" class="card-title"><h5 class="card-title">Ver Pruebas</h5></a>
    </div>
</div>

OlSoftwareFront/Views/Login/Index.cshtml
@model OlSoftwareFront.Model.Autentication
@{
    ViewData["Title"] = "Autentnicacion";

}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OlSoftwareFront</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OlSoftwareFront.styles.css" asp-append-version="true" />
</head>

<div class="container">
    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-header">Autenticacion</div>
        <div class="card-body">

            @using (Html.BeginForm("Login", "Login", FormMethod.Post, new { id = "FormProducto" }))
            {

                <!-- Agrega aquí los campos del formulario -->
                <div class="form-row">

                    <div class="form-group ">
                        <label>Username</label>
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })

                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label>Password</label>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @required = "required" } })

                    </div>
                </div>
              <br/>
                <br />
                <br />
                <div class="form-row">
                    <button type="submit" class="btn btn-light">Enviar</button>
                </div>
            }
        </br>
    </div>

</div>

OlSoftwareFront/Views/Prueba/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}